[tool.poetry]
name = "three-blind-mice"
version = "0.1.0"
description = ""
authors = ["Jessica Rakijas <jbrakijas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
playsound = "1.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
